config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'sessions/new'
  resources :events, only: %i[new index show create]
  resources :users, only: %i[new create show index]
  resources :attendances, only: %i[create update destroy]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  enum status: { invited: 0, accepted: 1 }
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }

  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, inverse_of: :creator
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  validates :name, presence: true, uniqueness: true, length: { minimum: 4, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :events_attendance, :events_created, :attend, :user_find_invited,
                :user_find_accepted
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def authorization
    redirect_to login_path, alert: 'Sign up or Log in to see the events!' unless current_user
  end

  def events_attendance
    current_user.attended_events
  end

  def events_created
    current_user.events
  end

  def attend(user)
    Attendance.find_by(event_id: params[:event_id], user_id: user.id)
  end

  def user_find_invited
    User.find(@event.attendances.invited.map(&:user_id))
  end

  def user_find_accepted
    User.find(@event.attendances.accepted.map(&:user_id))
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    attendance = Attendance.new(event_id: event.id, user_id: params[:user_id])

    if attendance.save
      attendance.invited!
      flash[:notice] = 'Invitation sent!'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Ooops! Something went wrong...'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    attendance = Attendance.find(params[:id])
    if current_user == event.creator
      attendance.destroy
      flash[:notice] = 'The invitation is cancelled!'
    else
      attendance.status = 'invited'
      attendance.save
      flash[:notice] = "You have dropped attending the #{event.name}!"
    end

    redirect_to users_path(event_id: event.id, id: attendance.id)
  end

  def update
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @attendance&.invited?
      @attendance.accepted!
      flash[:notice] = "Thank you for signing up for the '#{@event.name}'!"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end

  private

  def attendance_params
    params.require(:attendance).permit(:name, :date, :user_id, :event_id, :status)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :authorization
  helper_method :events_user_attending, :test

  def index
    @event = Event.all
    @past_events = Event.past.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
    @upcoming_events = Event.upcoming.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(events_params)
    if @event.save
      redirect_to event_path(@event), notice: 'Event created successfully'
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      session[:user_id] = user.id
      redirect_to events_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Name is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end

  def index
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :authorization, except: %i[create new]

  def index
    @user = User.all
    @user_reject = @user.reject { |user| user == Event.find(params[:event_id]).creator }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'user was successfully created'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navlinks
    links = []
    if logged_in?
      links[0] = link_to current_user.name.to_s, user_path(current_user), class: 'nav-link'
      links[1] = link_to 'Create Event', new_event_path(@event), class: 'nav-link'
      links[2] = link_to 'Logout', logout_path(@user), class: 'nav-link', method: :delete
    else
      links[0] = link_to 'Sign up', new_user_path(@user), class: 'nav-link'
    end
    links
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def events_params
    params.require(:event).permit(:name, :date, :location, :description, :user_id)
  end

  def event_invite
    users = []
    if user_find_invited.any?
      user_find_invited.each do |user|
        users << user.name
      end
    end
    users
  end

  def event_accepted
    users = []
    if user_find_accepted.any?
      user_find_accepted.each do |user|
        users << user.name
      end
    end
    users
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:name)
  end

  def events_empty
    events = []
    if @user.events.empty?
      events << 'User is not hosting'
    else
      @user.events.each do |event|
        events << (link_to event.description, event_path(event))
      end
    end
    events
  end

  def planned_event
    events = []
    if @user.attended_events.upcoming.count.zero?
      events << 'No planned Events'
    else
      @user.attended_events.upcoming.each do |event|
        events << (link_to event.description, event_path(event))
      end
    end
    events
  end

  def old_event
    events = []
    if @user.attended_events.past.count.zero?
      events << 'No Events Attended'
    else
      @user.attended_events.past.each do |event|
        events << (link_to event.description, event_path(event))
      end
    end
    events
  end
end

app/views/events/_futureevents.html.erb
<div class="d-flex justify-content-center">
  <% @upcoming_events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.description %></h5>
          <p class="card-text">Creator: <%= event.creator.name %></p>
            <div>
              <p class="font-1em">Event Date: <%= event.date %></p>
            </div>
            <div>
              <%= link_to 'Events to be hosted', event_path(event), class: "btn btn-primary"%>
            </div>
        </div>
      </div>
  <% end %>
</div>

app/views/events/_pastevents.html.erb
<div class="d-flex justify-content-center">
  <% @past_events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.description %></h5>
          <p class="card-text">Creator: <%= event.creator.name %></p>
            <div>
              <p class="font-1em">Event Date: <%= event.date %></p>
            </div>
            <div>
              <%= link_to 'Hosted events', event_path(event), class: "btn btn-primary"%>
            </div>
        </div>
      </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1 class="text-center normal my-3 bg-secondary w-50 mx-auto py-2 text-white">
    Upcoming events: <%=pluralize(@upcoming_events.count, 'Event')%>
  </h1>
  <div class="row"> 
    <%= render "futureevents"%>
  <div class="digg_pagination w-75 m-auto text-center">
    <%= will_paginate @upcoming_events, class: 'align=center' %>
  </div>
  </div>
  <h1 class="text-center normal my-3 bg-secondary w-50 mx-auto py-2 text-white">
    Past events: <%=pluralize(@past_events.count, 'Event')%>
  </h1>
  <div class="row">
    <%=render "pastevents" %>
    <div class="digg_pagination w-75 m-auto text-center">
    <%= will_paginate @past_events, class: align="center" %>
    </div>
  </div>

</div>

app/views/events/new.html.erb
<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@event.errors.count, "error") %> prohibited this user from being saved:</h2>
 
       <ul>
         <% @event.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <div class="field">
      <%= form.label :description %><br/>
      <%= form.text_field :description %>
  </div>

  <div class="field">
      <%= form.label :date %><br/>
      <%= form.date_field :date %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>

  <div class="field">
    <div class="control">
      <%= link_to 'Cancel', root_path, class:"button is-large is-fullwidth" %>
    </div>
  </div>

<% end %>

app/views/events/show.html.erb
<div class="section">
  <div class="container event-show d-flex align-items-center">
        <div class="card event-container mx-auto">
          <h5 class="card-header"><%= @event.description %></h5>
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <div>
                <p><small>Hosted by</small></p>
                <h4 ><%= @event.creator.name %></h4>
              </div>
    
              <div class="d-flex justify-content-between">
                <div class="dropdown">
                  <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <span>Invitees: <%= user_find_invited.count %></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% event_invite.each do |user|%>
                    <li><p class="dropdown-item"><%= user %></p></li>
                    <% end %>
                  </ul>
                </div>
                <div class="dropdown">
                  <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <span>Attendees: <%= user_find_accepted.count %></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% event_accepted.each do |user|%>
                    <li><p class="dropdown-item"><%= user %></p></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          <div class="ml-auto">
          <p class="card-header-title is-centered">Event Date: <%= @event.date %></p>
          </div>
          <br/>

          <% if @event.creator == current_user %>
            <%= button_to "Invite", users_path, params: {:event_id => @event.id}, method: :get, class: "btn btn-primary w-100" %>
          <% else %>
            <% attendance = Attendance.find_by(event_id: @event.id, user_id: current_user.id) %>
            <% if attendance && attendance.accepted? %>
              <%= button_to "Cancel attendance", attendance_path(id: attendance.id, event_id: @event.id, user_id: current_user.id), method: :delete, class: "btn btn-danger w-100" %>
            <% else %>
              <%= button_to "Enroll", attendance_path(event_id: @event.id), method: :patch, class: "btn btn-success w-100" %>
            <% end %>
          <% end %>

          <br/>

          <%= link_to 'Back to Event List', root_path, class: "btn btn-light border border-secondary w-100" %>
          </div>
          </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, msg| %>
<ul class="bg-primary my-0">
  <li><%= msg %></li>
</ul>  
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Private Events', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item"> <%= navlinks[0]%> </li> 
      <li class="nav-item"> <%= navlinks[1]%> </li>
      <li class="nav-item"> <%= navlinks[2]%> </li>  
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/messages' %>
     <%= render 'layouts/nav' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <div class="w-500px mx-auto">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6">Guest List</h2>
    
          <div class="columns is-centered">
            <table class="table is-fullwidth is-hoverable">
              <tbody>
                <th class="has-text-centered">Name</th>
                <th class="has-text-centered">Status</th>
                <th class="has-text-centered">Action</th>
                <% @user_reject.each do |user| %>
                  <% attendance = attend(user) %>
                  <tr>
                    <td class="has-text-centered">
                      <%= user.name %>
                    </td>
                    <% unless attendance.nil? || attendance.status.nil? %>
                      <td class="has-text-centered">
                        <span class="tag is-primary is-medium is-light"><%= attendance.status %><span>
                      </td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <% if attendance.nil? %>
                      <td class="has-text-centered">
                        <%= button_to "Invite", attendances_path(event_id: params[:event_id], user_id: user.id), class: "btn btn-success   btn-sm" %>
                      </td>
                    <% else %>
                      <td class="has-text-centered">
                        <%= button_to "Cancel Invitation", attendance_path(id: attendance.id, event_id: params[:event_id]), method: :delete, class: "btn btn-danger btn-sm" %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
                </tbody>
            </table>
          </div>

          <br/>

          <%= link_to 'Back to Event Details', event_path(id: params[:event_id]), class: "button is-fullwidth" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main-container d-flex align-items-center justify-content-center">
  <div class="login-container">
    <%= form_with(model: @user, local: true) do |form| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
          <%= form.label :name %><br/>
          <%= form.text_field :name, class: 'form-control'%>
      </div>

      <div class="actions">
        <%= form.submit "Sign Up", class: "btn btn-primary mt-2"%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
	  <div>
        <h2 class="title is-2 is-spaced has-text-centered"><%= @user.name %>'s Profile</h2>
      <div>
	      <div class="row">
          <div class="col-4">
            <h3 class="subtitle is-3 has-text-centered">Hosted Events: <%= @user.events.count %></h3>
            <ul>
               <% events_empty.each do |event| %>
                  <li><%= event %><li>
               <% end %>
            </ul>
          </div>

          <div class="col-4">
            <h3 class="subtitle is-3">Upcoming Events: <%= @user.attended_events.upcoming.count %></h3>
            <ul>
              <% planned_event.each do |event| %>
                <li><%= event %></li>
              <% end %>
            </ul>
          </div>

          <div class="col-4">
            <h3 class="subtitle is-3 has-text-centered">Attended Events: <%= @user.attended_events.past.count %></h3>
            <ul>
              <% old_event.each do |event| %>
                <li><%= event %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>